

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.DB_URL }}
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
