name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [closed]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set execute permission on gradlew
      run: chmod +x ./gradlew

    - name: Remove existing application.yml
      run: rm -f src/main/resources/application.yml

    - name: Create application.yml from secret
      run: echo "${{ secrets.APPLICATION_YAML }}" > src/main/resources/application.yml

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/safe-t .

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/safe-t

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: ubuntu-latest
  
    steps:
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client
  
    - name: Add SSH key
      run: echo "${{ secrets.EC2_SSH_KEY }}" > key.pem && chmod 600 key.pem
  
    - name: SSH and Run Docker Commands on EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
          # Ensure Docker is installed and running
          sudo systemctl start docker
          sudo usermod -aG docker ubuntu

          # Ensure changes are applied (log out and log back in to apply group changes)
          sudo su - ubuntu -c "exit"

          # Stop any existing containers with the same name
          sudo docker stop safe-t 2>/dev/null || true

          # Remove any existing containers with the same name
          sudo docker rm safe-t 2>/dev/null || true

          # Pull Docker image
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/safe-t

          # Run new container with explicit name
          sudo docker run -d -p 8080:8080 --name safe-t ${{ secrets.DOCKERHUB_USERNAME }}/safe-t

          # Check container logs for errors
          sudo docker logs safe-t

          # Clean up unused Docker images
          sudo docker system prune -f
        EOF
